-- Llaves Foráneas para APUESTAEVENTO

ALTER TABLE APUESTAEVENTO
ADD CONSTRAINT FK_APUESTA_EVENTO_USUARIO_ID
FOREIGN KEY (USUARIOID)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE APUESTAEVENTO
ADD CONSTRAINT FK_APUESTA_EVENTO_PARTIDO_ID
FOREIGN KEY (PARTIDOID)
REFERENCES PARTIDO(IDPARTIDO);

ALTER TABLE APUESTAEVENTO
ADD CONSTRAINT FK_APUESTA_EVENTO_EVENTO_ID
FOREIGN KEY (EVENTOID)
REFERENCES EVENTO(IDEVENTO);

ALTER TABLE APUESTAEVENTO
ADD CONSTRAINT FK_APUESTA_EVENTO_EQUIPO_ID
FOREIGN KEY (EQUIPOID)
REFERENCES EQUIPO(IDEQUIPO);

-- Llaves foráneas para APUESTAJUGADOR

ALTER TABLE APUESTAJUGADOR
ADD CONSTRAINT FK_APUESTAJUGADOR_USUARIO
FOREIGN KEY (USUARIOID)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE APUESTAJUGADOR
ADD CONSTRAINT FK_APUESTAJUGADOR_PARTIDO
FOREIGN KEY (PARTIDOID)
REFERENCES PARTIDO(IDPARTIDO);


ALTER TABLE APUESTAJUGADOR
ADD CONSTRAINT FK_APUESTAJUGADOR_JUGADOR
FOREIGN KEY (JUGADORID)
REFERENCES JUGADOR(IDJUGADOR);

--Llaves foráneas para APUESTAMARCADOR

ALTER TABLE APUESTAMARCADOR
ADD CONSTRAINT FK_APUESTAMARCADOR_USUARIO
FOREIGN KEY (USUARIOID)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE APUESTAMARCADOR
ADD CONSTRAINT FK_APUESTAMARCADOR_PARTIDO
FOREIGN KEY (PARTIDOID)
REFERENCES PARTIDO(IDPARTIDO);

--Llaves foráneas para CONTRATACION

ALTER TABLE CONTRATACION
ADD CONSTRAINT FK_CONTRATACION_JUGADOR
FOREIGN KEY (IDJUGADOR)
REFERENCES JUGADOR(IDJUGADOR);

ALTER TABLE CONTRATACION
ADD CONSTRAINT FK_CONTRATACION_EQUIPO
FOREIGN KEY (IDEQUIPO)
REFERENCES EQUIPO(IDEQUIPO);

--Llaves foráneas para EQUIPO

ALTER TABLE EQUIPO
ADD CONSTRAINT FK_EQUIPO_TECNICO
FOREIGN KEY (IDTECNICO)
REFERENCES TECNICO(IDTECNICO);

--Llaves foráneas para ESTADISTICA

ALTER TABLE ESTADISTICA
ADD CONSTRAINT FK_ESTADISTICA_PARTIDO
FOREIGN KEY (PARTIDOID)
REFERENCES PARTIDO(IDPARTIDO);

ALTER TABLE ESTADISTICA
ADD CONSTRAINT FK_ESTADISTICA_JUGADOR
FOREIGN KEY (JUGADORID)
REFERENCES JUGADOR(IDJUGADOR);

-- Llaves foráneas para EVENTO

ALTER TABLE EVENTO
ADD CONSTRAINT FK_EVENTO_PARTIDO
FOREIGN KEY (PARTIDOID)
REFERENCES PARTIDO(IDPARTIDO);

ALTER TABLE EVENTO
ADD CONSTRAINT FK_EVENTO_EQUIPO
FOREIGN KEY (EQUIPOID)
REFERENCES EQUIPO(IDEQUIPO);

--Llaves foráneas para METODOPAGO

ALTER TABLE METODOPAGO
ADD CONSTRAINT FK_METODOPAGO_USUARIO
FOREIGN KEY (USUARIOID)
REFERENCES USUARIO(IDUSUARIO);

-- Llave primaria compuesta para PARTICIPACION
ALTER TABLE PARTICIPACION
ADD CONSTRAINT PK_ID_TORNEO_EQUIPO
PRIMARY KEY (IDEQUIPO, IDTORNEO);

-- Llaves foráneas para PARTIDO

ALTER TABLE PARTIDO
ADD CONSTRAINT FK_PARTIDO_TORNEO
FOREIGN KEY (TORNEOID)
REFERENCES TORNEO(IDTORNEO);

ALTER TABLE PARTIDO
ADD CONSTRAINT FK_PARTIDO_ESTADIO
FOREIGN KEY (ESTADIOID)
REFERENCES ESTADIO(IDESTADIO);

ALTER TABLE PARTIDO
ADD CONSTRAINT FK_PARTIDO_EQUIPOLOCAL
FOREIGN KEY (EQUIPOLOCALID)
REFERENCES EQUIPO(IDEQUIPO);

ALTER TABLE PARTIDO
ADD CONSTRAINT FK_PARTIDO_EQUIPOVISITANTE
FOREIGN KEY (EQUIPOVISITANTEID)
REFERENCES EQUIPO(IDEQUIPO);

-- Llaves foráneas para TRANSACCION

ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_METODOPAGO
FOREIGN KEY (METODOPAGOID)
REFERENCES METODOPAGO(IDMETODOPAGO);

-- Llaves foráneas para USUARIO

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_ROL
FOREIGN KEY (ROLID)
REFERENCES ROL(IDROL);